// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrARFlopMFtBOx71YjxkxrtDJnEXmf6eU',
    appId: '1:201638917613:ios:94c3a0f63934c78d9f23e4',
    messagingSenderId: '201638917613',
    projectId: 'officesyndrome-2c1f6',
    storageBucket: 'officesyndrome-2c1f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrARFlopMFtBOx71YjxkxrtDJnEXmf6eU',
    appId: '1:201638917613:ios:94c3a0f63934c78d9f23e4',
    messagingSenderId: '201638917613',
    projectId: 'officesyndrome-2c1f6',
    storageBucket: 'officesyndrome-2c1f6.firebasestorage.app',
    iosBundleId: 'com.application.officesyndrome',
  );
}
